<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Post>
 */
class PostFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $body = "<p>    Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure doloribus inventore natus. Maxime inventore aperiam neque architecto, illo magnam provident voluptates quae tempora nisi totam nihil doloribus enim quas atque harum ut voluptatibus unde? Voluptatum, ipsa temporibus dicta aspernatur fugit magni est cupiditate eius corporis dolorem a error eligendi veniam expedita et. Ducimus accusantium inventore est quibusdam! Nihil sit fuga deserunt similique voluptates, dolores dignissimos harum impedit praesentium reiciendis, illo odio. Hic numquam et non repellat recusandae, est vero maiores sit ducimus iusto, qui, fuga debitis similique ab distinctio vel aut ex amet velit. Doloremque tenetur recusandae, suscipit eveniet accusantium nihil aspernatur officia? Asperiores eos quasi veniam aliquam ad eaque rerum soluta, neque dolores et, enim delectus laudantium, repellendus nostrum autem esse voluptates. Eveniet saepe perspiciatis enim aut cumque est. Aliquam temporibus quos eaque, odio placeat vero aliquid error saepe? Est suscipit ad odit sit adipisci? </p>
        <br>
        <p>    Delectus a sit cumque doloribus debitis corporis amet quaerat asperiores explicabo totam aliquam illum porro animi itaque, exercitationem saepe consequatur! Dicta, at molestias? Unde mollitia debitis tenetur quibusdam adipisci deleniti labore sunt numquam cumque amet nostrum, sit iste, repudiandae accusantium possimus ipsam! Pariatur repellendus error ducimus tempore fuga assumenda eaque, voluptates, exercitationem a veniam corporis maxime quos hic laudantium cumque quibusdam ipsa vitae vero magni, nisi totam blanditiis beatae. Culpa repudiandae numquam ratione adipisci! Harum impedit accusantium et tempore architecto reprehenderit optio qui fugit! Aliquid ut rem dignissimos error ducimus alias eum voluptatum, iusto fugiat, laboriosam obcaecati omnis sit. Adipisci eos inventore, earum, cupiditate vel asperiores tempore nemo est sunt, neque vero architecto fuga modi molestias doloremque provident accusantium beatae deleniti. Consectetur pariatur, aspernatur temporibus nam illo porro ipsum, totam, hic ab odio veniam animi tenetur ipsam explicabo placeat! Quo magni iusto nihil dolorem nesciunt quos ab laborum, cum suscipit ullam vitae.</p>
        <br>
        <p>    Fuga sed sequi nobis sapiente explicabo enim assumenda accusantium. Doloribus sunt aperiam maxime ipsum repellendus nihil sit dolore accusamus aliquam nesciunt sequi perferendis voluptas molestias cupiditate quia nemo optio ad adipisci placeat, asperiores voluptates reiciendis! Doloribus, iusto ducimus harum temporibus quia totam, unde atque maiores ullam perspiciatis quaerat nemo hic optio eos nulla, repudiandae accusantium. Atque, incidunt sed ratione culpa laudantium debitis. Laborum est natus et amet eveniet, esse ex sunt? Fuga sint facilis saepe dolorum numquam? Sunt dicta, est cum, architecto illo eveniet officiis ipsum, molestiae iste numquam pariatur incidunt ad. Odit voluptas veniam, doloribus labore animi delectus nemo expedita amet quasi architecto ducimus et rerum cumque similique nobis corporis culpa quos ad distinctio, sunt optio suscipit error. Necessitatibus omnis architecto accusantium facilis inventore blanditiis, modi, saepe officiis voluptatem, eaque assumenda fugiat minima ratione illo doloribus quae rem nulla. Totam tempore molestiae dolores voluptate officia modi iste ipsum consequuntur aut doloremque quibusdam, praesentium cumque rerum vel inventore iure quidem reprehenderit eligendi eveniet officiis voluptatum quae mollitia quis. Rem rerum debitis alias pariatur, quibusdam velit architecto consequatur, omnis autem voluptatibus, magni sequi. Error rerum amet laudantium impedit debitis placeat inventore possimus quaerat voluptatem a similique natus minus, atque cupiditate maiores numquam. Officia sed expedita vero dolores! </p>
        <br>
        <p>    Mollitia quam blanditiis delectus rem alias officia odio reprehenderit sequi rerum repellat eos aliquam dicta ipsam ipsum, nesciunt omnis? Doloremque aliquam esse consectetur sit nemo temporibus vitae ipsa, accusamus provident aliquid earum, a, rerum suscipit consequuntur. Temporibus ab, suscipit nulla ipsam ad, quam pariatur voluptatibus error, praesentium nisi laboriosam beatae corrupti repellendus illum nemo iste odit dolore perspiciatis voluptatem inventore ipsa exercitationem quisquam? Error culpa neque sit nesciunt reprehenderit voluptatibus ratione sint suscipit saepe cumque aspernatur, consequatur iure ipsam sequi nisi aliquam numquam earum atque optio quis, explicabo perferendis distinctio! Sapiente rem soluta quasi doloremque nihil eligendi? Tempore quasi fuga, quia ratione vitae reprehenderit nesciunt sed id nam optio sequi minus non quaerat corrupti nemo eveniet, a culpa repudiandae ipsa eos! Molestiae nam sunt cum nobis laborum recusandae numquam sed. Provident et sit fuga amet atque ipsam, ratione accusamus facere fugiat magnam pariatur voluptatum eum neque tempora quas quasi corporis veniam culpa vitae nesciunt veritatis officia alias dicta exercitationem? Atque voluptatem nemo rem, officia minus quo. Rerum laudantium repudiandae eius, quae sapiente ullam nam necessitatibus ipsam aperiam beatae consequuntur! Ullam rem dolor tempore laborum deserunt repellat assumenda sit aliquam voluptate mollitia nostrum nobis debitis recusandae eos error saepe, voluptatem laboriosam quibusdam adipisci perspiciatis officia sed maxime. Itaque quam obcaecati nisi expedita labore cumque ex dicta iure quae adipisci provident, aperiam illum dolore a quibusdam distinctio nostrum exercitationem doloribus in ab nihil? Ipsum maxime vitae debitis ab! Eum cupiditate similique aperiam, temporibus beatae commodi ipsa, debitis inventore deleniti magnam dolores enim rerum placeat nostrum, voluptatum ipsam sunt maiores eligendi eos earum reiciendis harum accusamus. Illo, corrupti maiores temporibus aperiam perspiciatis et amet quam officiis dolorem nulla quis, sunt sapiente vero ratione odit ipsum unde, mollitia consequuntur sequi modi nobis adipisci similique! Dolorem nemo odit sed nisi. Quibusdam maxime alias facilis delectus eligendi velit voluptatem, culpa saepe qui, incidunt ut reiciendis odio quod eum, quam voluptatum facere eius quia magnam possimus recusandae. Nihil adipisci sit eveniet sint quidem corporis, consequatur ipsam, labore voluptate assumenda culpa, quaerat sunt. Nobis, nemo possimus?</p>
        <br>
        <p>    Laudantium adipisci aspernatur reprehenderit officiis officia asperiores eligendi aut ipsam laborum mollitia facere vitae labore praesentium, delectus ipsa illum natus et blanditiis tenetur in tempore perspiciatis beatae. Ut sunt itaque neque at! Provident fugiat aliquid fugit! Sint perspiciatis autem illo doloremque qui perferendis nihil, repellendus ducimus, inventore minima nisi, totam aut eius provident dolorum distinctio ex quidem? Dignissimos odit mollitia quo aperiam obcaecati itaque repellendus maiores voluptates tempora, placeat laboriosam repudiandae. Quae exercitationem laboriosam reiciendis delectus aliquam odit a, alias illo voluptas. Qui, iure, unde doloribus officia totam molestiae ducimus ab vel laboriosam optio tempore delectus illo nulla eveniet quos. Libero nemo omnis officiis minima autem nesciunt laborum saepe, eum, hic quae iure aperiam fuga, tempora cumque harum voluptatem qui repellendus doloremque ratione quibusdam nam? Reiciendis aspernatur, non quidem nam explicabo sit libero dicta totam neque voluptatem porro impedit hic consectetur! Mollitia beatae explicabo ipsa, minus consequatur omnis illum quasi fugiat modi iste! Soluta voluptates ipsam asperiores in!</p>";

        return [
            "title" => fake()->title(),
            "slug" => fake()->slug() . "_" . date("Y-m-d_H-i-s"),
            "body" => $body,
            "excerpt" => Str::limit(strip_tags($body), 100, "..."),
            "user_id" => 1,
            "uploaded_at" => date("Y-m-d H-i-s"),
        ];
    }
}
